"""change-relation-subject-professors

Revision ID: 064d303cd3b3
Revises: a51de279c6ce
Create Date: 2025-02-09 09:31:09.872162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '064d303cd3b3'
down_revision: Union[str, None] = 'a51de279c6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professors', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'professors', 'subjects', ['subject_id'], ['id'])
    op.drop_constraint('subjects_ibfk_2', 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'professor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('professor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subjects_ibfk_2', 'subjects', 'professors', ['professor_id'], ['id'])
    op.drop_constraint(None, 'professors', type_='foreignkey')
    op.drop_column('professors', 'subject_id')
    # ### end Alembic commands ###
