"""add-qualifiaction-progam_type-entities

Revision ID: 5084e0da3d3b
Revises: f9ac680370fa
Create Date: 2025-02-08 18:55:39.181797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5084e0da3d3b'
down_revision: Union[str, None] = 'f9ac680370fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_types_id'), 'program_types', ['id'], unique=False)
    op.create_table('qualification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('review', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualification_id'), 'qualification', ['id'], unique=False)
    op.drop_constraint('courses_ibfk_1', 'courses', type_='foreignkey')
    op.drop_column('courses', 'program_id')
    op.add_column('professors', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('programs', sa.Column('program_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'programs', 'program_types', ['program_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'programs', type_='foreignkey')
    op.drop_column('programs', 'program_type_id')
    op.drop_column('professors', 'description')
    op.add_column('courses', sa.Column('program_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('courses_ibfk_1', 'courses', 'programs', ['program_id'], ['id'])
    op.drop_index(op.f('ix_qualification_id'), table_name='qualification')
    op.drop_table('qualification')
    op.drop_index(op.f('ix_program_types_id'), table_name='program_types')
    op.drop_table('program_types')
    # ### end Alembic commands ###
